# Generated by Django 3.2 on 2021-05-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctordetail',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
                ('d_email', models.EmailField(max_length=20)),
                ('d_pwd', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Registerdetail',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(max_length=35)),
                ('h_email', models.EmailField(max_length=20)),
                ('h_pwd', models.CharField(max_length=15)),
                ('h_address', models.CharField(max_length=50)),
                ('h_pincode', models.IntegerField()),
            ],
        ),
    ]
