# Generated by Django 3.1 on 2021-03-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_patient_fname', models.CharField(max_length=15)),
                ('ap_patient_lname', models.CharField(max_length=15)),
                ('ap_patient_email', models.EmailField(max_length=30)),
                ('ap_patient_number', models.CharField(max_length=10)),
                ('cancer_type', models.CharField(max_length=15)),
                ('ap_time', models.DateTimeField()),
                ('ap_label', models.TextField()),
                ('ap_doc_fname', models.CharField(max_length=15)),
                ('ap_doc_lname', models.CharField(max_length=15)),
            ],
        ),
    ]
