# Generated by Django 3.1 on 2021-04-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
                ('d_email', models.EmailField(max_length=20)),
                ('d_pwd', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(max_length=35)),
                ('h_email', models.EmailField(max_length=20)),
                ('h_pwd', models.CharField(max_length=15)),
                ('h_address', models.CharField(max_length=50)),
                ('h_pincode', models.IntegerField()),
            ],
        ),
    ]
