# Generated by Django 3.1 on 2021-04-21 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_doctor_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='d_name',
            new_name='d_fname',
        ),
        migrations.AddField(
            model_name='doctor',
            name='d_lname',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
