# Generated by Django 3.1 on 2021-04-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20210421_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
